### ISSUE TITLE
[SOLVED] - Not working after a few weeks,  V.1.1 upgrade made no difference. Did the Claude AI website change and cause the app to stop working?

### ISSUE THREAD

**Issue by frownbreaker** [dliedke/DeleteAllClaudeHistory#1]
Hi thanks for this utility, useful.

The apps worked fine for a few weeks (I invoke if via a shortcut to a batch file on my desktop)
I think the Claude UI changed and it stopped working.
I just updated to V1.1 but still have the same issue.

Any ideas? Happy to provide more info should you need it.

ChromeDriver was started successfully.
Opening in existing browser session.
Unhandled exception. System.InvalidOperationException: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Program Files\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.) (SessionNotCreated)
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
   at OpenQA.Selenium.WebDriver.ExecuteAsync(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.StartSession(ICapabilities capabilities)
   at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
   at OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options)
   at DeleteAllClaudeHistory.Program.Main(String[] args) in C:\GitLab\DeleteAllClaudeHistory\Program.cs:line 89

C:\Users\Seth\Desktop\DeleteAllClaudeHistory_v1.0>pause

**Comment by frownbreaker** [comment]
Tried clearing all cookies still no luck.

I killed Chrome and got some different message when invoking from the command line. I can see the Claude web page open and its logged in so I see my history appear, then this error:

C:\Users\Seth\Desktop\DeleteAllClaudeHistory_v1.0>DeleteAllClaudeHistory.exe  0<input.txt
Using saved email: XXXXXXXX
Press Enter to continue or type a new email to change:
Found profile: Default
ChromeDriver was started successfully.

DevTools listening on ws://127.0.0.1:56830/devtools/browser/93e87065-5874-4c60-83b2-20f04399c977

Total chats found: 14
An error occurred: element click intercepted: Element <a class="hover:bg-bg-400 group -mx-1.5 flex items-center gap-1 rounded-md px-1.5 py-1 transition-colors duration-200 font-tiempos text-text-200 text-sm" href="/chat/8e306bd7-c238-41a3-a4f9-75c843be17ce">...</a> is not clickable at point (120, 265). Other element would receive the click: <div class="min-h-full w-full min-w-0 flex-1">...</div>
  (Session info: chrome=126.0.6478.128)

C:\Users\Seth\Desktop\DeleteAllClaudeHistory_v1.0>pause
Press any key to continue . . .

**Comment by dliedke** [comment]
Hello @frownbreaker 

I am no longer support this project because I fixed some tempermonkey script to accomplish the same action in a more smooth way.

Tampermonkey extension:
[https://chromewebstore.google.com/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=pt-BR&pli=1](https://chromewebstore.google.com/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=pt-BR&pli=1)

Tampermonkey Script: Claude - Clear chat history:
[https://greasyfork.org/en/scripts/499085-claude-clear-chat-history/code](https://greasyfork.org/en/scripts/499085-claude-clear-chat-history/code)

Make sure to access the URL below for the extension to be activated:
[https://claude.ai/new](https://claude.ai/new)


Also autoclear for ChatGPT is pretty cool

Autoclear ChatGPT History:
[https://greasyfork.org/en/scripts/460805-autoclear-chatgpt-history](https://greasyfork.org/en/scripts/460805-autoclear-chatgpt-history)

**Comment by dliedke** [comment]
<img width="532" alt="image" src="https://github.com/user-attachments/assets/b503ed25-db9d-41ec-936f-8a50c1385d85">

**Comment by dliedke** [comment]
<img width="528" alt="image" src="https://github.com/user-attachments/assets/acd9067b-bcf7-4fe1-a157-f3edd8f78b21">
